### PR TITLE
Further fixes

### PR DESCRIPTION
**Pull request by robxnano**
Hi again. I've made some more fixes for the hotkey commands in SDL 1.2, as well as a change to stop SheepShaver from using the SDL Wayland video driver to work around a crash on Fedora 36. Finally I made some fixes to allow the emulators to be built with X11 video instead of SDL. This works OK in Basilisk II but SheepShaver has some problems that make it unusable at the moment, so it would need further work if anyone wanted to use it. Tested on Fedora 36 and Debian 10.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
In this pull request, video_sdl2.cpp does not need to be changed.
Please exclude it.
I recommend to use the names `opt_down` and `cmd_down` in other sources.

**Comment by robxnano** [comment]
Actually there is a reason for the changes to video_sdl2.cpp. It fixes a bug where the Alt and Super keys both triggered the hotkey even when only one of them was supposed to, when `swap_opt_cmd` was set to true. I've simplified the code now so the hotkeys only depend on the keycodes sent by SDL, rather than the ones from the keycode file.

I changed the names to `alt_down` and `super_down` so they would better match the SDL and X11 keycode names. For example SDL uses `SDLK_LGUI` to refer to the Windows/Command/Super key and `SDLK_LALT` for the Alt/Option key. If you want it to match the macOS key names, then it might be better to use combined names such as `opt_alt_down` and `cmd_super_down`.

**Comment by RonaldPR** [comment]
One needs to take into account that things need to work with both Windows keyboards and Mac keyboards. It took a lot of work and testing by different users with different setups, on different host OSs, and on different hardware to make the use of the option and command keys (as seen in the emulator) work as transparant as possible with different combinations of host OS, keyboard, (default)`swap_opt_cmd` setting, and with or without the new keycodes file. I hope that the proposed changes will not change this.

**Comment by kanjitalk755** [comment]
> I've simplified the code now so the hotkeys only depend on the keycodes sent by SDL, rather than the ones from the keycode file.

This specification is incorrect.
For example, there is a problem when using a German keyboard on a Windows host.

https://www.emaculation.com/forum/viewtopic.php?t=10515

**Comment by robxnano** [comment]
I understand your concerns. But this change only applies to the hotkeys used by the emulator itself, not the keycodes passed to the guest. I don't think it makes much sense to apply the keycode file to these commands since the "mouse grabbed, press Alt+F5 to release" message always refers to the keys as the names that the host OS uses. I think users would expect to use the actual keys with those names, since it's a function that exists outside the emulated operating system.

**Comment by kanjitalk755** [comment]
Honestly, I don't think the fix is ​​significant enough to change the source which has been tested with different types of keyboards and hosts.

**Comment by robxnano** [comment]
I think all the changes should be reverted now. Is this acceptable now?

**Comment by kanjitalk755** [comment]
Yes, thanks.

**Pull request merged**
