### PR TITLE
Fix building on SDL 1.2

### PR DESCRIPTION
**Pull request by robxnano**
This patch fixes SheepShaver/BasiliskII to compile and run using SDL 1.2 (although the startup audio and set gamma functions won't do anything). Tested on Rocky Linux 8.6 and Ubuntu 18.04.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
Couldn't build under Debian version 11.4.
```
g++ -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_linux -DDIRECT_ADDRESSING -DUNALIGNED_PROFITABLE -DX86_64_ASSEMBLY -DOPTIMIZED_FLAGS -DUSE_JIT -DUSE_JIT_FPU -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -fno-merge-constants -fno-gcse-sm -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -c ./../SDL/video_sdl.cpp -o obj/video_sdl.o
./../SDL/video_sdl.cpp: In function ‘bool VideoInit(bool)’:
./../SDL/video_sdl.cpp:1185:99: error: invalid new-expression of abstract class type ‘SDL_monitor_desc’
 1185 |  SDL_monitor_desc *monitor = new SDL_monitor_desc(VideoModes, (video_depth)color_depth, default_id);
      |                                                                                                   ^
./../SDL/video_sdl.cpp:362:7: note:   because the following virtual functions are pure within ‘SDL_monitor_desc’:
  362 | class SDL_monitor_desc : public monitor_desc {
      |       ^~~~~~~~~~~~~~~~
In file included from ./../SDL/video_sdl.cpp:64:
./../include/video.h:256:15: note:     ‘virtual void monitor_desc::set_gamma(uint8*, int)’
  256 |  virtual void set_gamma(uint8 *gamma, int num) = 0;
      |               ^~~~~~~~~
./../SDL/video_sdl.cpp: In function ‘void update_display_static(driver_base*)’:
./../SDL/video_sdl.cpp:1961:24: warning: comparison between ‘const enum video_depth’ and ‘enum<unnamed>’ [-Wenum-compare]
 1961 |   if (VIDEO_MODE_DEPTH < VIDEO_DEPTH_8BIT) {
make: *** [Makefile:194: obj/video_sdl.o] エラー 1
```

**Comment by robxnano** [comment]
I've fixed the problem with the latest commit. By the way, there are two versions of SDL 1.2 in Debian. libsdl1.2-compat is a compatibility layer for 2.0, while libsdl1.2 is the original. The compat version behaves differently, but there's no reason to use it when the proper 2.0 version is available and has more features. So I think 1.2 support is only needed for distributions that don't have 2.0.

**Comment by kanjitalk755** [comment]
You fixed the window title when mouse grab, but that is wrong.
For example, if `hotkey` is 7, it should be "(mouse grabbed, press Ctrl+Alt+Super+F5 to release)".

**Comment by kanjitalk755** [comment]
Couldn't be built.
```
g++ -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_linux -DDIRECT_ADDRESSING -DUNALIGNED_PROFITABLE -DX86_64_ASSEMBLY -DOPTIMIZED_FLAGS -DUSE_JIT -DUSE_JIT_FPU -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -fno-merge-constants -fno-gcse-sm -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -c ./../SDL/video_sdl.cpp -o obj/video_sdl.o
./../SDL/video_sdl.cpp: In function ‘void set_window_name(bool)’:
./../SDL/video_sdl.cpp:530:9: error: ‘s’ was not declared in this scope
  530 |         s += GetString(STR_WINDOW_TITLE_GRABBED_PRE);
      |         ^
./../SDL/video_sdl.cpp: In function ‘void update_display_static(driver_base*)’:
./../SDL/video_sdl.cpp:1966:24: warning: comparison between ‘const enum video_depth’ and ‘enum<unnamed>’ [-Wenum-compare]
 1966 |   if (VIDEO_MODE_DEPTH < VIDEO_DEPTH_8BIT) {
make: *** [Makefile:194: obj/video_sdl.o] エラー 1
```

**Pull request merged**
