### PR TITLE
For non-X11 GTK, don't depend on X11

### LINKED ISSUE #29: Build fails for non-X11 GTK
Building fails on Mac OS X with GTK present.

```
main_unix.cpp:136:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
2 warnings and 1 error generated.
make: *** [obj/main_unix.o] Error 1
```

GTK was detected by autotools and the GTK GUI was enabled automatically, but the GTK it found is Quartz-based, not X11 based; the system does not have X11 by default.

### PR DESCRIPTION
**Pull request by rakslice**
Fixes #29.

### CODE REVIEW

**Comment by rakslice** [comment]
For the case where GTK is X11 case and the inclusion and `XInitThreads` call is enabled, I wonder if there is something missing the autotools side to go with this?

**Comment by rakslice** [comment]
Does this work for GTK 1.2? Is that supported in BasiliskII/Sheepshaver?

**Comment by rakslice** [comment]
From `configure.ac` it seems BasiliskII supports GTK 1.2.  It seems that GTK 1.2 does not define `GDK_WINDOWING_X11`, so this would fail in the sense of not including the `XInitThreads` call for X11-based GTK 1.2.

**Comment by kanjitalk755** [comment]
Adopted another implementation.

**Pull request closed without merging**
