### PR TITLE
Cross Platform Bin/Cue Support for CD Audio

### PR DESCRIPTION
**Pull request by spolsley**
### Overview

I've been working on re-enabling and expanding the old bin/cue code from Geoffrey Brown and the DosBox team in small snatches over the past year.  I think it's finally ready to merge.  Here's a brief description of what's in the PR:

- In order to play mixed-mode games or use Apple's CD Audio player, you need a bin/cue image of the original CD since that's the only way to preserve CD audio.
- This code updates both BasiliskII and SheepShaver to support mounting bin/cue images.  To use, add ".cue" files from bin/cue pairs to preferences as "cdrom"s.
- CD audio uses SDL2, and should work on Mac, *nix, and Windows hosts, compiled using the "--with-bincue" flag.

### Notes

- CD audio now uses SDL2's improved AudioStream to support mixing 44khz 16-bit stereo with any other audio.  The CoreAudio headers (e.g., MacOSX/AudioDevice, etc.) have been updated to compile against Apple's latest APIs, but I haven't tested extensively.  SDL audio is probably a better option since its cross-platform and already leverages CoreAudio on Mac hosts.
- A couple bin/cue modes have been added, including yellow book and pure data image types.
- CD rom handling has been expanded with the implementation of a few more system calls, including audio functions for start/stop/scanning and so on.
- Any number of cue sheets can be added to preferences and all will mount as their own drives on the Desktop.
  + Mac OS doesn't really handle multiple audio CDs, typically defaulting to the first drive in the list.  This is a case where the emulator can actually add functionality over original hardware.  By monitoring which drive was most recently used, we can make an educated guess about which is intended for the current audio call.  This works for many games since they tend to access data on the disc while playing, but you can also force it by opening the CD for data access, like viewing a file in Finder.
  + While multiple audio CDs can be mounted at once, only one is allowed to play at a time to avoid overlapping audio or any other confusion.  Playing CDs are automatically paused if audio from another CD is loaded.

### For Future

- Scaffolding for a sound input driver has been expanded but not fully implemented.  It's using the native driver at the moment, which uses digital audio as of Mac OS 9 and appears to load fine in SheepShaver.  Ideally, more of the sound input driver can be implemented to allow applications like microphone input.
- Multiple bin/cue files can cause slightly unpredictable behavior.  For instance, Descent loads its menu entirely from hard disk, so it will start playing with the default CD at launch.  However, once a game begins, it reads some data from the CD and audio is corrected.  The easiest fix is to mount a single audio CD at a time.
- Older games written specifically for Apple's built-in CD player, like Warcraft 1, don't yet work with this method.  Better SCSI support or some other feature may be needed.

### More Info

- There is a [thread at Emaculation](https://www.emaculation.com/forum/viewtopic.php?f=20&t=10220) tracking some relevant discussions related to this feature
- [Pre-built binaries](https://github.com/spolsley/macemu/releases/tag/20200707) are available for testing.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
Host: macOS10.15.5

* I confirmed that BII built by automake is OK.
But other cases (BII built by Xcode, SS built by automake/Xcode) are no good.
Specifically, no music listed in AppleCD Audio Player.
In such cases, work well if disable optimization (-O0).
Can you fix the PR so that it works with optimization enabled?

* If all "TRACK" in the cue file are "AUDIO", BII/SS crash because row_sector_size is 0.
Is this the specification?

**Comment by spolsley** [comment]
- Ah, good catch! I had forgotten the debug optimization setting, and turning it on, I can replicate the issue.  The lack of tracks is tied to some missing variable initializations.  However, that's exposed another problem when using the player for play/pause actions; I think it's a race condition with the player position given that it's also changed in the audio thread.

- I actually didn't think to test pure audio CDs since my focus was mixed-mode.  The original Red-book spec was for pure digital audio, and it should be possible to remove the need for mounting a data partition.  I'll have to make an audio CD bincue and experiment with that.

Thanks for the feedback!  I'll push fixes/updates when I can get to the bottom of the optimization issue.

**Comment by spolsley** [comment]
Ok, I've pushed a couple fixes.  They were pretty much entirely memory and initialization issues.

- For optimization, the lingering problem was setting a value outside the array bound when accessing player frame position by pointer.

- For audio CDs, I've set the initial sector size based on a pure audio disc, since data modes must be specified in the standard.  However, I'm having difficult creating a functioning bin/cue for an audio CD, maybe a copy protection issue.  Do you have such an image to test with?

**Comment by kanjitalk755** [comment]
macOS: OK
  linux: OK (build only)
Windows: OK (build only)

> Do you have such an image to test with?

Unfortunately I don't have any data available.
Needless to say, you can edit the cue file to create dummy data.

I have a request.
In Xcode project of both BII and SS, please set optimization level to -O0 for Debug and -O3 for Release.

**Comment by spolsley** [comment]
Optimization levels set now.

I took a mixed-mode disc and set the data portion to AUDIO so it produces static but the other tracks played properly, so I believe a pure audio CD would work as well.

**Pull request merged**
