### PR TITLE
Restoring sound DRVR patch for New World ROMs

### PR DESCRIPTION
**Pull request by spolsley**
Issue: When not using "ignoresegv true", certain ROMs can crash on boot if DRVR -16501 (0xbf8b) is not patched over.  This issue originated in my testing with bin/cue cd playthrough, and I failed to identify the error using ignoresegv.

This proposed fix patches -16501 to allow booting without ignoresegv.  However, -16500 (0xbf8c) replaces sound input with a currently broken driver from audio.cpp which prevents certain games from playing CD audio.  If the crash can be prevented without patching this driver, I think it will support more applications until audio.cpp can be more fully implemented.  This code seems to be sufficient for both cases (booting without ignoresegv and playing games that require CD playthrough), but if it continues to cause problems, I can update the PR as needed. 🙂

### CODE REVIEW

**Comment by rakslice** [comment]
This change, to patch -16501 but not -16500, does not allow booting without ignoresegv in my testing:

```
SIGSEGV
  pc 089fac23
  ea 61f14000
 r0 00000000   r1 17ff5890   r2 00000000   r3 50f14000
 r4 00000040   r5 fffffffa   r6 00003540   r7 ffffffe8
 r8 00110477   r9 61776163  r10 0000bf8c  r11 00000384
r12 0000001e  r13 61776163  r14 00000000  r15 00000001
r16 001e0f4e  r17 000a7ef0  r18 0011fdc0  r19 0010d05a
r20 17ff5a9e  r21 001a68b6  r22 17ff59da  r23 00000000
r24 001e0f7e  r25 00000000  r26 00000000  r27 000050f1
r28 001be0c4  r29 40c89e00  r30 40c60000  r31 68fff000
 f0 0.00000   f1 0.00000   f2 0.00000   f3 0.00000
 f4 0.00000   f5 0.00000   f6 0.00000   f7 0.00000
 f8 0.00000   f9 0.00000  f10 0.00000  f11 0.00000
f12 0.00000  f13 0.00000  f14 0.00000  f15 0.00000
f16 0.00000  f17 0.00000  f18 0.00000  f19 0.00000
f20 0.00000  f21 0.00000  f22 0.00000  f23 0.00000
f24 0.00000  f25 0.00000  f26 0.00000  f27 0.00000
f28 0.00000  f29 0.00000  f30 0.00000  f31 0.00000
 lr 40c89e00  ctr 00000000   cr 40001c22  xer 00000000
 pc 40c89fe0 fpscr 00000000
  0x40c89fc0:  lbz     r4,0(r27)
  0x40c89fc4:  b       0x40c66330
  0x40c89fc8:  ori     r5,r30,25396
  0x40c89fcc:  b       0x40c65e2c
  0x40c89fd0:  lbzx    r4,r24,r27
  0x40c89fd4:  b       0x40c66330
  0x40c89fd8:  ori     r5,r30,25396
  0x40c89fdc:  b       0x40c65ea8
 >0x40c89fe0:  clrlwi  r4,r27,24
  0x40c89fe4:  b       0x40c66330
  0x40c89fe8:  lwz     r5,2048(r31)
  0x40c89fec:  b       0x40c6d6b0
  0x40c89ff0:  lwz     r5,2048(r31)
  0x40c89ff4:  b       0x40c6d6b0
  0x40c89ff8:  lwz     r5,2048(r31)
  0x40c89ffc:  b       0x40c6d6b0
  0x40c8a000:  rlwinm  r4,r8,24,0,7
```

If you're changing the approach to sound such that ROM code will now do some known reads in the I/O area, you could add them to the list in `sigsegv_handler()` in `sheepshaver_glue.cpp`...

**Comment by rakslice** [comment]
The existing codebase doesn't seem to have to do this for anything else in the I/O area so I suspect the general approach to this kind of read is to patch the ROM so it isn't even attempted.

**Comment by spolsley** [comment]
I'm wondering if this is tied to the guest OS.  Are you running Mac OS 8?  I was able to reproduce the crash once in Mac OS 8, but it's not happening regularly, nor have I encountered it in Mac OS 9.  The difference I notice is that Mac OS 9 displays sound input options like CD playthrough while Mac OS 8 does not.

My main hope is to keep support for CD playthrough, so perhaps your suggestion of ignoring it in the sigsegv handler is best for now; ignoresegv = true has been bypassing this with no problem for all guests.  Alternatively, I'm still unsure what aspects of the sound input driver are missing that it's not loading from audio.cpp.  Patching that could be a fix for pre-OS 9 guests.

**Comment by rakslice** [comment]
This was with a 9.0.4 installation and also the 9.0 install CD. I didn't try any other OS versions.

**Comment by spolsley** [comment]
Ah, I’ll have to do some testing in my Windows setup to try reproducing the crash. I’m not as familiar as I’d like to be with the rom patches and driver implementations but will try to piece together what I can!

**Comment by rakslice** [comment]
Wait, Mac OS 8.0/8.1 doesn't work with a new world ROM. Do you mean 8.5+?

**Comment by spolsley** [comment]
Yes, sorry about the ambiguity.  8.5+

I have been able to reproduce this on occasion with OS 9 as well now.  I'm seeing what regions of the ROM might be affected while also experimenting with the audio.cpp driver.

**Comment by rakslice** [comment]
No worries, I was just curious if there was some kind of configuration mix-up. In my testing I get the crash 100% of the time for New World ROMs on across platforms, CPUs, etc. It's not intermittent at all.

**Comment by kanjitalk755** [comment]
I committed a provisional fix for this issue.

**Comment by rakslice** [comment]
@kanjitalk755 It seems that does not catch everything, for instance `ROMBase + 0x46628c`, the one that I reported in the original issue kanjitalk755/macemu#46  Are you able to reproduce this?

**Comment by kanjitalk755** [comment]
I can't reproduce that.
To fix it formally, we will need to implement a sound input driver which can support bin/cue.

**Comment by kanjitalk755** [comment]
I could reproduce the issue in Mingw.
And it turned out that it is impossible to judge by the pc.

To avoid a crash, I changed that if New World ROM is used and "ignoresegv" is false, patch the sound input driver.

This is only a temporary measure.

**Comment by spolsley** [comment]
Using `ignoresegv` does seem simplest in the meantime.  I've been working more on the sound input driver but still have issues getting it to fully load; Apple's documentation is unfortunately light on some details.

I suppose another option is to identify the source of the crashes to see if the native driver could load, maybe a fake endpoint for the microphone is needed.  I know Sheepshaver has a bit of a reputation for being hacky, so getting the native driver able to load would be a good option, but I'm trying to find any other documentation or sources which could help.

**Comment by spolsley** [comment]
After some fiddling, I have a barebones patched driver for CD playthrough.  Interestingly, I thought I'd have to implement the record function.  However, in limited testing, it looks like some games rely on the input driver to check for an internal CD device that supports playthrough.  After that, the CD driver is used for audio play directly.  It seems even a simple patch without recording or options can function, but I'll need to test more and cleanup the code.  Hopefully, I can update/replace the PR in the next day or two.

As a small aside, I noticed the latest gamma code is maxing out screen brightness on Mac builds, even when the device is set lower.  I can make a separate issue for that if you'd like; just haven't explored it much yet.

**Comment by kanjitalk755** [comment]
> As a small aside, I noticed the latest gamma code is maxing out screen brightness on Mac builds, even when the device is set lower. I can make a separate issue for that if you'd like; just haven't explored it much yet.

Please make a new issue with the details of the problem.

**Comment by spolsley** [comment]
@rakslice Can you confirm if this new patch boots without ignoresegv on your setup?  It's running for me here, but I couldn't reproduce all of the issues you encountered and am unsure if there's anything still causing trouble.

This driver patches the ROM with a new .AppleSoundInput called Built-in, just like the original, but it presents only two sources: Microphone and Internal CD.  It presents itself as having playthrough and a few other features.  The options dialog is not implemented, and there is no line in source available right now.  It could be added without much trouble, and actually if anyone wants to extend the SoundOpen routines to capture and send audio, including microphone input would be possible.

**Comment by kanjitalk755** [comment]
SS works fine, but BII cannot be built with errors.

**Comment by spolsley** [comment]
Ack, I keep forgetting something!  I switched the vm_memcpy provided by kpx_cpu to Host2Mac_memcpy from cpu_emulation.h.  It should be semantically better, plus BasiliskII can now build and run.

Although this discussion is related to NewWorld roms, I'll mention that OldWorld ROMs are still loading the native sound input driver.  This doesn't seem to be causing a crash, except in BII if you try to make changes under Sound preferences.  I examined a Power Mac 7200 ROM ([96CD923D](https://docs.google.com/spreadsheets/d/1wB2HnysPp63fezUzfgpk0JX_b7bXvmAg6-Dk7QDyKPY/edit#gid=840977089)) with [tbxi](https://github.com/elliotnunn/tbxi) but don't see any audio input DRVRs other than ids -16501, -16500, and -16495.  No effect in Sheepshaver but maybe if the patch were added in BII, it would load the fake driver as well.

**Comment by kanjitalk755** [comment]
It seems to be okay, so merged it once.

**Pull request merged**
