### PR TITLE
fix for slirp ftp handling putting slirp placeholder address in PORT commands

### PR DESCRIPTION
**Pull request by rakslice**
If the outside address of the listening socket for the data connection is the placeholder `alias_addr` value, use `getsockname()` to get the local side address of the established control connection which is the actual local address.

This is analogous to what `tcp_subr.c` is already doing for the ident protocol https://github.com/kanjitalk755/macemu/blob/03e159338732095c7da536681900677f6c5a5ede/BasiliskII/src/slirp/tcp_subr.c#L675

If for some reason `getsockname()` doesn't work on a platform, I fall back to slirp's general idea of the local address, usually a hostname reverse lookup. 
https://github.com/kanjitalk755/macemu/blob/03e159338732095c7da536681900677f6c5a5ede/BasiliskII/src/slirp/misc.c#L89
In a typical configuration this is a localhost address equally useless to a remote server, but it at least allows for manually configuring something better in e.g. `/etc/hosts`

I haven't made any attempt to handle IPv6 here.

**Background:**

In ordinary FTP in normal "active" mode:
1. The client makes a control connection to the server
2. When a data connection is needed for an upcoming command, the client sets up a listening socket for the data connection and sends a `PORT` command with its address and the port of the listening socket
3. The client sends the command needing the data connection, and the server attempts to establish the data connection by connecting back to the address and port given

How FTP handling for NAT works:
1. The NAT intercepts and relays FTP control connections (e.g. TCP port 21)
2. When a `PORT` command is encountered, the NAT sets up for a one-shot inbound connection from the next available outside port to the inside address and port in `PORT` command
3. The NAT sends a replacement `PORT` command with its outside address and the chosen outside port

### CODE REVIEW

**Comment by rakslice** [comment]
Fixes #208

**Comment by rakslice** [comment]
I guess there's no official upstream slirp codebase that macemu uses that this change should go to instead?

**Comment by kanjitalk755** [comment]
Confirmed FTP active mode can now be used.

> I guess there's no official upstream slirp codebase that macemu uses that this change should go to instead?

May be the following repository?

https://gitlab.freedesktop.org/slirp/libslirp

**Comment by rakslice** [comment]
I mean, fair, that's _more_ maintained, but it has diverged so far I can't even tell in short order where `so_faddr` on a listening socket is even set

**Pull request merged**
