### PR TITLE
GTK 3 support

### PR DESCRIPTION
**Pull request by robxnano**
This pull request adds support for building with GTK 3. I've rewritten the prefs editor UI in XML to make it easier to modify, and fixed some error message boxes that previously didn't work. If GTK 3 is not found, it will fall back to building with GTK 2.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
The following files contain changes unrelated to GTK.

BasiliskII/src/Unix/prefs_unix.cpp
BasiliskII/src/Unix/user_strings_unix.cpp
BasiliskII/src/Unix/user_strings_unix.h
BasiliskII/src/cdrom.cpp
BasiliskII/src/include/user_strings.h
BasiliskII/src/rom_patches.cpp
BasiliskII/src/user_strings.cpp

SheepShaver/src/CrossPlatform/sigsegv.cpp
SheepShaver/src/Unix/user_strings_unix.cpp
SheepShaver/src/Unix/user_strings_unix.h
SheepShaver/src/include/user_strings.h
SheepShaver/src/rom_patches.cpp
SheepShaver/src/user_strings.cpp

Exclude them and create another PR if necessary.

**Comment by robxnano** [comment]
I've removed everything I could, but I had to leave some strings that are needed in the GTK3 code.

**Comment by kanjitalk755** [comment]
1. In BasiliskII/src/Unix/main_unix.cpp, the GUI command line processing is incorrectly inserted into the `--switch` option processing.
Correct the insertion position.

1. The `ramsize` in prefs can also be written in megabytes for convenience when editing in text.
When reading, if this value is less than or equal to 1000, multiply it by 1024*1024.

**Comment by kanjitalk755** [comment]
> The `Resolution` is always initialized to `1024 x 768`, so fix it to follow the prefs.

Could you take a look at this?

**Comment by robxnano** [comment]
Sorry, I missed that one somehow.

**Comment by kanjitalk755** [comment]
The Windows build still uses GTK macros, so reverted.

**Pull request merged**
