### PR TITLE
Updated icons; add Windows medium icon

### PR DESCRIPTION
**Pull request by emendelson**
Replace the existing icons with the 7/8 design; add a 48x48 icon for the Windows build.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
BasiliskII_*_icon.c are not used for linux build.
Do you still want to merge these files?
If not, exclude these files.

**Comment by emendelson** [comment]
The icon.c files are used for the Windows build, but they are in the Unix folder. I don't know why they are there, but the Windows build uses them. Please try it and see. 

If you look at the code in Unix/video_x.cpp that I modified, you'll see that the comment says (correctly) that the icons are the Windows icons. Perhaps that code could be moved into a windows file, and the icons also moved to the Windows folder? But the revised code correctly builds the Windows executable with the correct icons, even though they are in the Unix folder.

**Comment by kanjitalk755** [comment]
Unix/video_x.cpp does not be used for Windows build.
See output of make.

**Comment by emendelson** [comment]
You are right. Windows caches desktop icons, and so my system displayed the old icon instead of the new one in shortcuts, directory listings, etc. So I thought it was necessary to fix the c files that said "Windows icons".

But it is enough to replace the .ico file. My apologies for wasting time!

**Pull request merged**
