### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RichCini**
These are the startup chime files. Calling this required changes to SDL_Main.m. Will post separately.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
Currently, it is implemented to play startup.wav (if it exists) at the end of SDL audio initialization.
This allows it to play on both BII and SS, regardless of platform.
In contrast, your implementation needs to make changes to multiple files.
This pull request cannot be adopted without a reasonable reason to change the current implementation.

**Comment by RichCini** [comment]
I'm indifferent where the call to PlayStartupChime() is made; whatever is easiest. I feel it should be placed after the main window is created and before the desktop appears. I put the actual sound code in its own source files to make it easier to move around the placement of the call.

I made the changes from my original code download from yesterday rather than a clean pull. Again, whatever works best.

**Comment by kanjitalk755** [comment]
There is currently no reason to merge this pull request, so I close it.
I think it's worth merging if the startup sound can be played at the right time on both BII and SS, and on all platforms.

**Comment by RichCini** [comment]
Thanks.

http://cini.classiccmp.org/
Long Island S100 User’s Group

Get Outlook<https://aka.ms/qtex0l> for iOS

________________________________

**Pull request closed without merging**
