### PR TITLE
Restore support for various Unix OSes

### PR DESCRIPTION
**Pull request by robxnano**
These changes are mostly to restore compatibility with other Unix operating systems, including FreeBSD, NetBSD and OpenIndiana. They were all supported previously, but other changes including the transition to 64-bit have ended up breaking them. Most of them still need work to fix them, but I'll have to leave that to others. Basilisk II works fine with these changes on FreeBSD though.

### CODE REVIEW

**Comment by kanjitalk755** [comment]
I tried this PR on Debian and it removed `-no-pie` from LDFLAGS due to a change in `configure.ac`.
The UAE CPU core does not run the JIT compiler without this flag.
Please fix.

**Comment by robxnano** [comment]
Before I make the changes, can I just ask whether SheepShaver needs the `-no-pie` flag as well? I want to know whether I should fix the test in the SheepShaver configure.ac, or just change it back so that it only checks for the macOS-specific `-Wl,-no_pie` flag.

**Comment by kanjitalk755** [comment]
SheepShaver seems to work without `no-pie` flag on all host types.

**Comment by kanjitalk755** [comment]
BasiliskII: On macOS, fix `LDFLAGS` to not contain `-no-pie`.

**Comment by robxnano** [comment]
@kanjitalk755 I think that should do it.

**Pull request merged**
