### PR TITLE
X64 32-bit address instruction skip

### PR DESCRIPTION
**Pull request by rakslice**
Add x86_64's `0x67` 32-bit address size prefix to `ix86_skip_instruction()`. Fixes rakslice/macemu#64

### CODE REVIEW

**Comment by kanjitalk755** [comment]
Is the same fix needed for BasiliskII/src/CrossPlatform/sigsegv.cpp?
If so, please add it to the PR.

**Comment by rakslice** [comment]
Done. Not required as such but there's no downside to keeping their `ix86_skip_instruction` implementations in sync.

**Comment by rakslice** [comment]
Do you happen to know why BasiliskII and SheepShaver `sigsegv.cpp` are already different? The difference is all `__APPLE__` `__x86_64__` sections that are only present for SheepShaver.

**Comment by kanjitalk755** [comment]
It's for JIT compiler of macOS version.
It should be accessible from address 0, which is not allowed on x86_64 binary since macOS 10.10.
So I patched the JIT code with address translation.
(SheepShaver/src/Unix/dyngen_precompiled/{basic,ppc}-dyngen-ops-x86_64_macos.hpp)
However, that is not enough and can cause SEGV.
Therefore, the instructions are emulated with address translation in sigsegv.cpp.

**Comment by rakslice** [comment]
Ah, I see.

The corresponding issue on Linux (mmap of 0 is disabled by a kernel tunable that the user may not have permission to change or may not want to) is why I'm trying to figure out what SheepShaver/src/Unix/dyngen_precompiled/{basic,ppc}-dyngen-ops-x86_{32,64}.hpp were originally built with, so I can just rebuild them with `configure --enable-addressing=direct`.

**Pull request merged**
